const express = require('express')
const app = express()
const mongoose = require('mongoose')
mongoose.connect("mongodb://192.168.0.129/customers")
const userroute = require('./src/route/customers')
const entityroute = require('./src/route/entityRouter')
const productroute = require('./src/route/productRouter')
const apitokenroute = require('./src/route/apiTokenRouter')
app.use(express.json())
app.use('/',userroute)
app.use('/entity',entityroute)
app.use('/product',productroute)
app.use('/apiToken',apitokenroute)
app.listen(3000)